name: naser_alqtami
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  audio_service: ^0.18.10
  audio_video_progress_bar: ^1.0.1
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.2.1+1
  equatable: ^2.0.5
  firebase_core: ^2.14.0
  firebase_dynamic_links: ^5.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_screenutil: ^5.8.4
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  get_it: ^7.6.0
  internet_connection_checker: ^1.0.0+1
  just_audio: ^0.9.34
  logger: ^1.4.0
  path_provider: ^2.0.15
  share_plus: ^7.0.2
  shared_preferences: ^2.1.2
  url_launcher: ^6.1.11
  webview_flutter: ^4.2.2
  youtube_player_flutter: ^8.1.2
  font_awesome_flutter: ^10.5.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/
    - assets/json/

  fonts:
    - family: Din
      fonts:
        - asset: assets/fonts/DINNEXTLTARABIC-LIGHT-2-2.ttf
          weight: 300
        - asset: assets/fonts/DINNextLTArabic-Medium-4.ttf
          weight: 400
        - asset: assets/fonts/DINNextLTArabic-Regular-4.ttf
          weight: 500
        - asset: assets/fonts/DINNextLTArabic-Bold-4.ttf
          weight: 700

# flutter_native_splash:
#   image: assets/images/logo_without_bg.png
#   background_image: assets/images/menu_bg.jpg
#   android: true
#   ios: true
