class AppStrings {
  static const String appName = 'ِAlqatami';
  static const String appNameArabic = 'تطبيق القطامي';

  static const String fontFamily = 'Cairo';
  static const String noRouteFound = 'No Route Found';
  static const String cachedRandomQuote = 'CACHED_RANDOM_QUOTE';
  static const String contentType = 'Content-Type';
  static const String applicationJson = 'application/json';
  static const String serverFailure = 'Server Failure';
  static const String cacheFailure = 'Cache Failure';
  static const String unexpectedError = 'Unexpected Error';


  static const List<String> youTubeVideosIds = [
    "Mtj-1WLUQdk",
    "m8jWgye0m4E",
    "ED3_2vOl2Po",
    "ZhXMyBB3Dlc",
    "N2_fziUv3ug",
    "vXCLbt6kWkk",
    "qzejZ-j2H1o",
    "o0d2UNqU6xU",
    "KCPM1Nq-H8k",
    "HRtfzXkMZFU",
    "1mOg9F5Uk44",
    "eNOdqHlYNe4",
    "_pHOikWidBA",
    "_jECWfpUO9Y",
    "CKlnlalrvdEv",
    "G-BpFpEm7Go",
    "pjQ4m2qodFE",
    "zknVDzyag38",
    "DOgx_DP6RKk",
    "cvsRrb894P8",
    "Ljmyf87OD04",
    "oHjKDkWNiYA",
    "t82xf_G5A_Q",
    "84huCDiYxcE",
    "WhsqYjcbdw8",
    "Ik6kGrwpmq4",
    "RJ6xxaalJAs",
    "VHkVu9xv8C0",
    "cqX8Nj0Rp0o",
    "f3LhCRBvjcI",
    "b2ye72ZdgFw",
    "M3wtl5Ld9Sc",
    "OIv0_P5f8sU",
    "_G_3GRKxmYA",
    "GrHtOIzwNOI",
    "0_Duhseqbs4",
    "gXUD-UtCPQs",
    "V3unKhj3l04",
    "gYRv0uVD1NA",
    "htwSnwsWjlo",
    "1z5eqc2HrU0",
    "1z5eqc2HrU0",
    "1z5eqc2HrU0",
    "s8jdcJnqmHw",
    "mWyAUCpmJKw",
    "kY6OtLAkYpw",
    "7Nl2I2PF9Pc",
    "A2XAoibVN7k",
    "nCZFBu28aDg",
    "UVcZNNF0iXY",
    "_YrGRQqauNY",
    "-G2ybmBW6Ao",
    "U9_cZJtP6-M",
    "qjnpj35Syp8",
    "C0k9Fvnplqg",
    "mmTT_bbDQ_Q",
    "CDSNVTRrKNE",
    "f96fT9tS7yY",
    "svEbLco3oCg",
    "W9LtFEm6IG8",
    "IhEkpaorK8U",
    "Gui1LCr1gXk",
    "1ty1KieCi78",
    "eyiq866lcX4",
    "UulCH4p06vU",
    "N7y8rN2A4lY",
    "RaAxWURaTnc",
    "9QFGQIcJtos",
    "TNI1pcY1PYU",
    "K_Ap4jZD2y0",
    "i10f00BPNMg",
    "f4jIPXGDmtE",
    "Shmjy56OoJE",
    "liKD-veB4dA",
    "zd8XTCCuxj4",
    "YAaq9UBCpSM",
    "j5_jMasH7NU",
    "x1t6FMkaisA",
    "31q_6bwIugM",
    "sCZoC4TJ7nE",
    "JU2zsHiQINM",
    "lcaZ43yIDnk",
    "YPEQuvlLeAU",
    "wjpgqussKZg",
    "xl5hokCHtnA",
    "xi_6pMxWVqU",
    "cVO5D2mRXh4",
    "q4Gj-5KTfs0",
    "SYXmVQH7CfE",
    "yYeUVphdEtw",
    "fOlilmnvzk4",
    "k5Jv2c2OFpg",
    "SMI9xQxLst0",
    "dRAvpgm7KZU",
    "2ZQoWxJic1o",
    "aWC1CeGLm7I",
    "26PD5MT9__k",
    "E-tLzhA8BZc",
    "yy2O8Y5rG3g",
    "6h-fwah_lSw",
    "VPsJyiDVPm0",
    "Q5ahnyWtsxk",
    "Uwb8JIm4jJ0",
    "kzzxG-YeBg4",
    "cPsgzrxkoxQ",
    "W3uvXp40rQI",
    "5dXQum8Vs8k",
    "4qzfe4omjUg",
    "UqrziYaprkE",
    "sGlR6Ffzh9A",
    "OckkWpC9z5c",
    "gI7IwQWWUEw",
    "iypibOmArc0",
    "n5-FMngMcgk",
    "yF_slFgdocA",
    "gR0edOEcOyE",
  ];
}
